# Generated by Django 5.0 on 2024-10-06 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="title",
            new_name="title",
        ),
    ]
